name: subrecovery
description: "A new Flutter project."
publish_to: "none"
version: 1.5.4
environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  csv: ^6.0.0
  shared_preferences: ^2.3.3
  flutter_easyloading: ^3.0.5
  get: ^4.6.6
  cached_network_image: ^3.4.1
  blur: ^4.0.0
  permission_handler: ^11.3.1
  image_gallery_saver_plus: ^3.0.5
  url_launcher: ^6.3.1
  dio: ^5.7.0
  flutter_local_notifications: ^18.0.1
  flutter_background: ^1.3.0+1
  package_info_plus: ^4.1.0
  just_audio: ^0.9.42
  flutter_screenutil: ^5.9.3
  window_manager: ^0.3.6
  chinese_lunar_calendar: ^0.0.13
  keframe: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # flutter_launcher_icons: ^0.9.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/photo/
    - assets/dictionary/
    - assets/chapter/
    - assets/icon/
    - assets/story/
    - assets/music/

flutter_icons:
  # flutter pub run flutter_launcher_icons:main -f pubspec.yaml
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.webp"
  min_sdk_android: 21
